---
# tasks file for webserver
- name: pull an image
  docker_image:
    name: 13.48.106.84:5000/webserver:v0.1
  
- name: container running
  docker_container:
    name: myapplication
    image: 13.48.106.84:5000/webserver:v0.1
    state: started
    ports:
      - "8080:8080"