---
# tasks file for docker_engine
- name: Ensure docker key is installed
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Ensure docker is installed
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'python3-pip'] 
    state: present
  become: yes

- name: Ensure docker-py is installed
  pip:
    name: docker-py

- name: Add user to docker group
  user:
    name: "{{ansible_user_id}}"
    groups: docker
    state: present